apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: setup-business-central
spec:
  # Set by pipeline-run
#  params:
#    - name: param1
#      type: string
#    - name: param2
#      type: string
  tasks:
    - name: list-resources
      taskRef:
        name: openshift-client
        kind: Task
      params:
        - name: SCRIPT
          value: "oc get all"
        